version: "3.8"

services: 
  mySQLDB:
    image: mysql
    container_name: mySQLDB
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports:
      - 4000:3306
    environment:
      MYSQL_USER: mysql
      MYSQL_PASSWORD: ex
      MYSQL_DATABASE: location
      MYSQL_ROOT_PASSWORD: ex
    volumes:
      - mysql_data:/var/lib/mysql
   
volumes:
  mysql_data:
   